server.port=8585
server.servlet.context-path=/workintech

spring.devtools.restart.enabled=true

management.endpoints.web.exposure.include=info,health,mappings
management.info.env.enabled=true

info.app.name=Spring Boot Dependency Injection
info.app.description=Developer CRUD uygulamasi
info.app.version=1.0.0